apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordsearch-db-pvc
  namespace: fernando0069-dev
  labels:
    app: wordsearch
    component: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3
---
kind: Secret
apiVersion: v1
metadata:
  name: wordsearch-db
  namespace: fernando0069-dev
  labels:
    app: wordsearch
    component: db-secret
data:
  POSTGRESQL_ADMIN_PASSWORD: RHIwd3NzNHAtdDAwcg==
  POSTGRESQL_DATABASE: d29yZHNlYXJjaC1kYg==
  POSTGRESQL_USER: d29yZHNlYXJjaC1kYg==
  POSTGRESQL_PASSWORD: YmQtaGNyNDNzZHIwVw==
type: Opaque
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wordsearch-db
  namespace: fernando0069-dev
  labels:
    app: wordsearch
    component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordsearch
      component: db
      deployment: wordsearch-db
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordsearch
        component: db
        deployment: wordsearch-db
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: wordsearch-db-storage
          persistentVolumeClaim:
            claimName: wordsearch-db-pvc
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: postgresql
          env:
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordsearch-db
                  key: POSTGRESQL_ADMIN_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: wordsearch-db
                  key: POSTGRESQL_DATABASE
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordsearch-db
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: wordsearch-db
                  key: POSTGRESQL_USER
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: wordsearch-db-storage
              mountPath: /var/lib/postgresql/data
          terminationMessagePolicy: File
          image: 'image-registry.openshift-image-registry.svc:5000/openshift/postgresql@sha256:8910bd59fcf917fc54f47342939ca3f828560f1881245ed3777ace21e0367963'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: wordsearch-db
  namespace: fernando0069-dev
  labels:
    app: wordsearch
    component: db-srv
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 5432-tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: wordsearch
    deployment: wordsearch-db
